# Generated by Django 5.0 on 2025-03-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesign', '0002_alter_aboutimage_title_alter_blogimage_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceimage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='videoimage',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
