# Generated by Django 5.0 on 2025-03-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesign', '0003_serviceimage_subtitle_alter_videoimage_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogimage',
            name='full_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
