# Generated by Django 5.0 on 2025-03-25 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codesign', '0004_blogimage_full_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogimage',
            name='full_content',
        ),
    ]
