# Generated by Django 5.0 on 2025-03-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesign', '0005_remove_blogimage_full_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogimage',
            name='full_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
