# Generated by Django 5.0 on 2025-03-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesign', '0006_blogimage_full_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogimage',
            name='prayer_points',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogimage',
            name='scripture',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
