# Generated by Django 5.0 on 2025-03-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesign', '0007_blogimage_prayer_points_blogimage_scripture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('deliverance', 'Deliverance')], max_length=50)),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
